url: go.uber.org
index_title: uber-go
packages:
  thriftrw:
    type: github
    github_user: thriftrw
    github_repo: thriftrw-go
    badges:
      - godoc
  yarpc:
    type: github
    github_user: yarpc
    github_repo: yarpc-go
    badges:
      - godoc
